# Generated by Django 5.2.3 on 2025-06-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='country',
            field=models.CharField(default='US', help_text='ISO 3166-1 alpha-2 country code', max_length=2),
        ),
    ]
